
---
- name: Provision VM
  hosts: localhost
  gather_facts: no

  tasks:
  
    - name: Test Role
      include_role:
        name: vmware


- name: Setup MSSQL
  hosts: "{{ hostvars['localhost']['created_vm_ip'] }}"
  gather_facts: no

  tasks:
  
    - name: Test Role
      include_role:
        name: mssql
